#!/usr/bin/env sh
basedir=`dirname $0`;
cd "$basedir"; srcpath=`pwd`
srcfile="$srcpath/git-m"
destlink="/usr/local/bin/git-m"

if [ ! -h "$destlink" -o "$FORCE" = "yes" ]; then
    ln -sf "$srcfile" "$destlink"
    exit $?
fi
echo "git-m has been linked."

exit 1
